### ISSUE TITLE
[FEATURE REQUEST] Plot example with SpeciesConc output

### ISSUE THREAD

**Issue by ktravis213** [geoschem/gcpy#156]
## Add your feature request below:
Hi support team.  As a new python user, it is not obvious to me how to adjust the benchmark example to get the right colorbar for a species in ppb.  I am trying to plot ozone, but this code gives me a colorbar from zero to 1.

import xarray as xr
import gcpy.plot as gcplot
import matplotlib.pyplot as plt
ds=xr.open_dataset('GEOSChem.SpeciesConcSubset.20160501_0000z.nc4')
o3 = ds['SpeciesConc_O3'].isel(lev=0,time=1)*1E9
gcplot.single_panel(o3,title='Surface Ozone')
plt.show()

Could you add an example to read the docs that changes the colorbar?
Thanks!

**Comment by Jourdan-He** [comment]
Hi @ktravis213 , could you try changing 
`gcplot.single_panel(o3,title='Surface Ozone')`
to 
`gcplot.single_panel(o3,title='Surface Ozone', vmin=a, vmax =b)`
where a and b are the lower and upper limits for the colorbar
Let me know if you have any other questions!

**Comment by ktravis213** [comment]
Thanks, I get this error when I do that.
"Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it."

**Comment by Jourdan-He** [comment]
I tried to reproduce your error with a different netcdf file, but I am able to change the range of colorbar. Could you attach your GEOSChem.SpeciesConcSubset.20160501_0000z.nc4 file so that I can take a look at?

**Comment by yantosca** [comment]
Hi @ktravis213 and @Jourdan-He... I think we might have fixed an issue like this before but it might be in the dev branch rather than in the main branch.  It was due to a package update (e.g. matplotlib I believe).  

See issue #155 for a list of package versions that work on my cluster.  You might need to update some of these.

**Comment by yantosca** [comment]
@ktravis213 @Jourdan-He: @SaptSinha For GCPy 1.3.0, I have figured out a new set of python package versions.  This will be in the `docs/source/environment.yml` file that ships with 1.3.0.
```yaml
name: gcpy
channels:
    - conda-forge
    - defaults
dependencies:
    - cartopy=0.19.0.post1            # Geospatial data processing
    - esmf==8.1.1                     # Earth system modeling framework
    - esmpy==8.1.1                    # Python wrapper for ESMF
    - netcdf4==1.6.0                  # Python wrapper for netCDF
    - netcdf-fortran==4.5.4           # Python wrapper for netCDF-Fortran
    - python==3.9.6                   # Python version 3.9.6
    - pip==21.2.1                     # Install packages from PyPi
    - sparselt>=0.1.3                 # Regridding earth system model data
    - xesmf==0.5.1                    # Universal regridder
    - pip:
        - awscli>=1.22.83             # Utilities for AWS cloud
        - dask==2021.7.1              # Parallel library; backend for xarray
        - docutils==0.16              # Convert text to other formats
        - h5netcdf==0.11.0            # Python interface to netCDF4/HDF5
        - h5py==3.3.0                 # Python interface to HDF5
        - matplotlib==3.4.2           # Creates plots and visualizations
        - jinja2==3.0.3               # Dependency for Sphinx
        - joblib==1.0.1               # Parallelize python code
        - numpy==1.21.1               # Optimized mathematical functions
        - pandas==1.3.1               # Tables/timeseries manipulation
        - pycodestyle==2.9.1          # Python style checker (formerly PEP8)
        - pylint==2.15.3              # Python linter
        - pypdf2==1.26.0              # PDF utilities (bookmarks, etc.)
        - recommonmark==0.7.1         # Dependency for Sphinx   
        - requests==2.26.0            # HTTP library
        - scipy==1.7.0                # Scientific python package
        - sphinx==3.5.4               # Generate ReadTheDocs output
        - sphinx-autoapi==1.9.0       # Sphinx autodoc style documentation
        - sphinx-autobuild==2021.3.14 # Build ReadTheDos live in browser
        - sphinxcontrib-bibtex==2.2.0 # ReadTheDocs bibliography style
        - sphinx_rtd_theme==0.5.2     # ReadTheDocs HTML theme files
        - tabulate==0.8.9             # Pretty-printing for column data
        - xarray==0.17.0              # Read data from netCDF etc files
```
Long story short: I now use specific package versions rather than `>=`, because we often find that when a package gets updated, it breaks backward compatibility with some other package.  Also we now get several packages from PyPI (pip) instead of conda-forge since that is usually quicker to install.

You can install with:

```console
$ conda env create -n gcpy --file=environment.yml
```
