### ISSUE TITLE
[BUG/ISSUE] OH metrics table lists wrong Ref and Dev

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gcpy#231]
In the header for GCClassic vs GCHP OH metrics tables, the Ref and Dev versions are the same.

See http://s3.amazonaws.com/benchmarks-cloud/diff-plots/1Mon/diff-gchp-c24-1Mon-14.2.0-alpha.15-gcc-4x5-1Mon-14.2.0-alpha.15/BenchmarkResults/GCHP_GCC_comparison/Tables/OH_metrics.txt.

```
###############################################################################
### OH Metrics
### Ref = gcc-4x5-1Mon-14.2.0-alpha.15
### Dev = gcc-4x5-1Mon-14.2.0-alpha.15
###############################################################################

------------------------------------------------------------
Global mass-weighted OH concentration [10^5 molec cm^-3]
------------------------------------------------------------
Ref      : 13.10319997289
Dev      : 13.11612003755
Abs diff :  0.01292006466
%   diff :  0.098602

------------------------------------------------------------
CH3CCl3 (aka MCF) lifetime w/r/t tropospheric OH [years]
------------------------------------------------------------
Ref      :  4.744647
Dev      :  4.720860
Abs diff : -0.023787
%   diff : -0.501349

------------------------------------------------------------
CH4 lifetime w/r/t tropospheric OH [years]
------------------------------------------------------------
Ref      :  8.004795
Dev      :  7.961379
Abs diff : -0.043417
%   diff : -0.542385
```

**Comment by yantosca** [comment]
@msulprizio @laestrada: I put in some debug statements into run_benchmark.py, and I used the rundirs from recent integration tests as placeholder folders:

In my `1mo_benchmark.yaml`
```yaml
 dev:
    gcc:
      version: gcc-14.2.0
      dir: GCC_it/rundirs/gc_4x5_merra2_fullchem_benchmark
      outputs_subdir: OutputDir
      restarts_subdir: Restarts
      bmk_start: "2019-07-01T00:00:00" 
      bmk_end: "2019-08-01T00:00:00"
    gchp:
      version: gchp-14.2.0
      dir: GCHP_it/rundirs/gchp_merra2_fullchem_benchmark
      outputs_subdir: OutputDir
      restarts_subdir: Restarts
      bmk_start: "2019-07-01T00:00:00" 
      bmk_end: "2019-08-01T00:00:00"
      is_pre_14.0: False
      resolution: c24
```
In my run_benchmark.py:
```python
    # =====================================================================
    # Plot title strings
    # For gchp_vs_gcc_refstr use config["data"]["dev"]["gcc"]["version"], not ref (mps, 6/27/19)
    # =====================================================================
    gcc_vs_gcc_refstr = config["data"]["ref"]["gcc"]["version"]
    gcc_vs_gcc_devstr = config["data"]["dev"]["gcc"]["version"]
    gchp_vs_gcc_refstr = config["data"]["dev"]["gcc"]["version"]
    gchp_vs_gcc_devstr = config["data"]["dev"]["gchp"]["version"]
    gchp_vs_gchp_refstr = config["data"]["ref"]["gchp"]["version"]
    gchp_vs_gchp_devstr = config["data"]["dev"]["gchp"]["version"]
    diff_of_diffs_refstr = bmk.diff_of_diffs_toprow_title(config, "gcc")
    diff_of_diffs_devstr = bmk.diff_of_diffs_toprow_title(config, "gchp")

    print(f"gchp_vs_gcc_refstr: {gchp_vs_gcc_refstr}")
    print(f"gchp_vs_gcc_devstr: {gchp_vs_gcc_devstr}")
    quit()
```
and I get this output:
```console
gchp_vs_gcc_refstr: gcc-14.2.0
gchp_vs_gcc_devstr: gchp-14.2.0
```
So it looks like the `run_benchmark.py` is reading the info from the YAML file and assigning to the labels OK.  Will take a look at the gc-cloud-infrastructure repo as well.
